name: Ubuntu


on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: sudo apt update && sudo apt install build-essential qt6-base-dev libqt6svg6-dev libgl1-mesa-dev ninja-build -y

    - name: Configure CMake
      shell: bash
      run: cmake -S $GITHUB_WORKSPACE -B build -DCMAKE_BUILD_TYPE=$BUILD_TYPE -G Ninja

    - name: Build
      shell: bash
      run: cmake --build build --config $BUILD_TYPE -j

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: spotify-qt
        path: ${{runner.workspace}}/build/spotify-qt
